-- MySQL Script generated by MySQL Workbench
-- Sun Nov  1 15:11:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`youtubeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`youtubeur` (
  `idyoutubeur` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `date_naissance` DATE NULL,
  `autreActivites` VARCHAR(128) NULL,
  `debut_youtube` DATE NULL,
  PRIMARY KEY (`idyoutubeur`),
  UNIQUE INDEX `idyoutubeur_UNIQUE` (`idyoutubeur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `idutilisateur` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(56) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idutilisateur`),
  UNIQUE INDEX `idutilisateur_UNIQUE` (`idutilisateur` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chaine` (
  `idchaine` INT NOT NULL,
  `nom_chaine` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `date_creation` DATE NOT NULL,
  `nb_abonnes` INT NOT NULL,
  `nb_videos` INT NOT NULL,
  `nb_vues` INT NOT NULL,
  `youtubeur_idyoutubeur` INT NOT NULL,
  UNIQUE INDEX `idchaine_UNIQUE` (`idchaine` ASC) VISIBLE,
  PRIMARY KEY (`idchaine`),
  INDEX `fk_chaine_youtubeur_idx` (`youtubeur_idyoutubeur` ASC) VISIBLE,
  CONSTRAINT `fk_chaine_youtubeur`
    FOREIGN KEY (`youtubeur_idyoutubeur`)
    REFERENCES `mydb`.`youtubeur` (`idyoutubeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chaine_has_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chaine_has_utilisateur` (
  `chaine_idchaine` INT NOT NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`chaine_idchaine`, `utilisateur_idutilisateur`),
  INDEX `fk_chaine_has_utilisateur_utilisateur1_idx` (`utilisateur_idutilisateur` ASC) VISIBLE,
  INDEX `fk_chaine_has_utilisateur_chaine1_idx` (`chaine_idchaine` ASC) VISIBLE,
  CONSTRAINT `fk_chaine_has_utilisateur_chaine1`
    FOREIGN KEY (`chaine_idchaine`)
    REFERENCES `mydb`.`chaine` (`idchaine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chaine_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
